name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Windows Package
        run: npm run make-win
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/make/**/*.exe
            out/make/**/*.msi
            out/make/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
